version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  mrz_build_deploy:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          args: pytest
      - run:
          name: Run Test
          command: |
            cd ssw567/mrz-scanner/tests/unit-test/
            pytest --junitxml=../reports/junit.xml MTTDtest.py
      - store_test_results:
          path: reports
workflows:
  ssw567:
    jobs:
      - mrz_build_deploy